- hosts: lamp
  sudo: yes
  tasks:

    - name: Check if MySQL is already installed.
      stat: path=/etc/init.d/mysql
      register: mysql_installed

    - name: Update apt cache if MySQL is not yet installed.
      apt: update_cache=yes
      when: mysql_installed.stat.exists == false

    - name: Add the repository for MySql 5.6
      become: yes
      command: add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty universe'

    - name: Update Package
      shell: sudo apt-get update && sudo apt-get upgrade -y
      args:
        executable: /bin/bash

    - name: Install python
      apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
      with_items:
        - sysstat
        - python-setuptools
        - python-dev
        - build-essential

    - name: Install pip
      shell: sudo easy_install pip
      args:
        executable: /bin/bash


