- hosts: lamp
  sudo: yes
  tasks:
    - name: Update Package
      shell: sudo apt-get update && sudo apt-get upgrade -y
      args:
        executable: /bin/bash

    - name: Install Apache
      apt: name=apache2 state=present

    - name: Install PHP module for Apache
      apt: name=libapache2-mod-php5 state=present

    - name: start Apache
      service: name=apache2 state=running enabled=yes