- hosts: lamp
  sudo: yes
  tasks:
    - name: Add key
      apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCBCB082A1BB943DB state=present

    - name: Add repository
      apt_repository: repo='deb http://ftp.osuosl.org/pub/mariadb/repo/10.0/ubuntu $ansible_distribution_release main' state=present update_cache=yes

    - name: Check if MySQL is already installed.
      stat: path=/etc/init.d/mysql
      register: mysql_installed

    - name: Update Package
      shell: sudo apt-get update && sudo apt-get upgrade -y
      args:
        executable: /bin/bash

    - name: Install python
      apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
      with_items:
        - sysstat
        - python-setuptools
        - python-dev
        - build-essential

    - name: Install pip
      shell: sudo easy_install pip
      args:
        executable: /bin/bash

    - name: Install Apache
      apt: name=apache2 state=present

    - name: Install PHP module for Apache
      apt: name=php-mysql state=present

    - name: Start Apache
      service: name=apache2 state=running enabled=yes

    - name: Install MariaDB
      apt: name=mariadb-server state=present

    - name: Start Mysql Service
      service: name=mysql state=started enabled=true

    - name: Install python Mysql package #required for mysql_db tasks
      apt: name=python-mysqldb state=present

    - name: Create a new database
      mysql_db: name=wp state=present collation=utf8_general_ci

    - name: Create a database user
      mysql_user: name=wp password=Qsx1@3esZ priv=*.*:ALL host=localhost state=present

    - name: Install MySQL extension for PHP
      apt: name=php5-mysql state=present

