- hosts: terraform.overagosts.info 
  sudo: yes
  tasks:
    - name: Deploy Terraform
      shell: cd /home/denisz/terraform/terraform/azure/ && terraform apply -auto-approve
      args:
        executable: /bin/bash
