- hosts: 35.198.125.114
  sudo: yes
  tasks:
    - name: Deploy Terraform
      shell: cd /home/denisz/terraform/terraform/azure/ && terraform destroy -auto-approve
      args:
        executable: /bin/bash
