- hosts: myVM
  gather_facts: yes
  sudo: yes
  tasks:

    - name: Update Package
      shell: sudo apt-get update && sudo apt-get upgrade -y
      args:
        executable: /bin/bash

    - name: Install the package "mc"
      shell: sudo apt-get install mc -y
      args:
        executable: /bin/bash

    - name: Install the package "htop"
      shell: sudo apt-get install htop -y
      args:
        executable: /bin/bash

    - name: Install the package "iptraf"
      shell: sudo apt-get install iptraf -y
      args:
        executable: /bin/bash

    - name: Install Apache2
      shell: sudo apt-get install apache2 -y 
      args:
        executable: /bin/bash

