- hosts: myVM
  connection: local
  gather_facts: yes
  sudo: yes
  tasks:
#    - name: Deploy Terraform
#      shell: terraform apply -auto-approve
#      args:
#        executable: /bin/bash
#      tags:
#        - pre-settings
    
    - name: Update Package
      shell: apt-get update && apt-get upgrade -y
      args:
        executable: /bin/bash

#    - name: Install nginx
#      shell: apt install nginx -y
#      args:
#        executable: /bin/bash

    - name: Install the package "mc"
      shell: apt-get install mc -y
      args:
        executable: /bin/bash

    - name: Install the package "htop"
      shell: apt-get install htop -y
      args:
        executable: /bin/bash

    - name: Install the package "iptraf"
      shell: apt-get install iptraf -y
      args:
        executable: /bin/bash

